### ISSUE TITLE
java.lang.NoSuchMethodError: com.google.common.io.CharSource.readLines(Lcom/google/common/io/LineProcessor;)Ljava/lang/Object;

### ISSUE THREAD

**Issue by dandan2611** [Litarvan/OpenLauncherLib#11]
Bonjour, j'ai un problème avec mon launcher que je n'arrive pas à régler

ERREUR 👎 

java.lang.NoSuchMethodError: com.google.common.io.CharSource.readLines(Lcom/google/common/io/LineProcessor;)Ljava/lang/Object;

**Comment by Litarvan** [comment]
Tu es sur le serveur donc tu sais qu'il y a une FAQ ( http://support.manercraft.fr/ ) et c'est marqué dessus, ça n'a aucun rapport avec la lib en elle même et donc ça n'a rien à faire ici ;)
