### ISSUE TITLE
OpenlauncherLib est il compatible avec les comptes Minecraft crack ?

### ISSUE THREAD

**Issue by ghost** [Litarvan/OpenLauncherLib#18]
Bonjour,
Je voudrais savoir et comment utiliser OpenLauncherLib pour les Comptes Crack, car je voudrais faire un launcher, qui pourrait avoir un mode premium et un autre mode, Crack, cela est il possible ?

**Comment by Litarvan** [comment]
Il suffit de fournir un authinfos avec n'importe quoi en token
