### ISSUE TITLE
Add MD5/SHA1 for old libraries

### ISSUE THREAD

**Issue by Bencor29** [Litarvan/OpenLauncherLib#19]
Bonjour,

Le lien vers la repo maven est mort ([https://litarvan.github.io/maven/](https://litarvan.github.io/maven/))

**Comment by Litarvan** [comment]
Bonjour,

Il n'existe pas de page d'accueil donc aller directement dessus donne une 404, en revanche il marche bien si l'on renseigne une dépendance.

Le 14 sept. 2019 00:46, Benjamin CORNOU <notifications@github.com> a écrit :

Bonjour,

Le lien vers la repo maven est mort (https://litarvan.github.io/maven/)

**Comment by Bencor29** [comment]
Ah bien vu, ils pourraient afficher le contenu du dossier comment beaucoup font pour pas qu'on se méprenne. Bref, j'avais utilisé la repo Litarvan.github.io et j'ai remarqué que mon serveur Jenkins m'envoyais des avertissements pour la vérification du checksum. Comptez-vous ajouter fichier sha1 et md5 ou pas ?

**Comment by Bencor29** [comment]
[https://pastebin.com/raw/zGj6WA9S](https://pastebin.com/raw/zGj6WA9S)

**Comment by Litarvan** [comment]
Il faudrait que je les ajoute effectivement, je le fais depuis longtemps mais je ne l'ai pas rajouté pour les anciens paquest du temps où je ne savais pas le faire. Je laisse l'issue ouverte le temps que je le fasse
