### ISSUE TITLE
Plus de souplesse pour choisir la ram

### ISSUE THREAD

**Issue by Bricklou** [Litarvan/OpenLauncherLib#9]
Bonjour,
Serait-il possible d'ajouter plus de souplesse sur le choix de la ram en remplaçant le JComboBox par un JTextField car pour le modpack que j'utilise sur mon pc de 4Go de ram, j'ai besoin d'une config de 3584Mo
et donc pour 3Go ce n'est pas assez et pour 4Go c'est trop.
Est-il possible de faire cela ?

Cordialement Bricklou.

**Comment by Litarvan** [comment]
Regarde un peu les sources, tu peux fournir ta propre frame au RamSelector et donc faire ce que tu veux ;)
